<a href="https://colab.research.google.com/github/kelvincent/Machine-learning-documentation/blob/Numpy-Array-and-scikit-learn/Machine_learning_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Refrence documentation**

In [5]:
import numpy as np
np.array?

In [28]:
np.con*?

**The use of ? and or *? is used to find the documentation **

### **Array Common Manipulation**

manual construction of array

In [7]:
#creating of single and multi array
a1 = np.array([2,4,5,7,11])
a1i = np.array([3,6,10,13,11])
a2= np.array([[1,4,8,9],[1,3,5,7]])
a2i= np.array([[2,4,7,5],[1,3,4,5]])


a1,a2,a1.shape,a2.shape

(array([ 2,  4,  5,  7, 11]),
 array([[1, 4, 8, 9],
        [1, 3, 5, 7]]),
 (5,),
 (2, 4))

In [8]:
#use of range function to evenly distribute numbers by increment and decrement
b1= np.arange(10)
b2= np.arange(11,20)
b3= np.arange(21,30,2)

b1,b2,b3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([21, 23, 25, 27, 29]))

In [ ]:

#another use of increment and decrement by point
c1= np.linspace(31,32,3)
c2= np.linspace(35,40,20)


c1,c2

In [10]:
#creating same types of array
e1 = np.ones((3,5))
e2= 7 * np.ones((3,3))
e3 = 0* np.ones((3,5))

e1,e2,e3

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [11]:

#common use of random function
f0 = np.random*?

f1 = np.random.rand(2,3)
f2 = np.random.rand(3,2)
f3= np.random.randn(2,3)
f4 = np.random.randn(3,2)

f5 = np.random.randint(5)
f6 = np.random.randint(10,15)
f7= np.random.randint(20,30,4)

#f8 = np.random.ranf(5)
#f9 = np.random.ranf(10.0,15.0)
#f10 = np.random.ranf(20.0,30.0,4.0)

In [12]:
#basic operation
#addition, subtraction, array multiplication and matrix multiplication
a1 -2, a1+2, a2, a2[:,2], a2[:,2]+1, a1*a1i, e1*e1,e2.dot(e2)

(array([0, 2, 3, 5, 9]),
 array([ 4,  6,  7,  9, 13]),
 array([[1, 4, 8, 9],
        [1, 3, 5, 7]]),
 array([8, 5]),
 array([9, 6]),
 array([  6,  24,  50,  91, 121]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[147., 147., 147.],
        [147., 147., 147.],
        [147., 147., 147.]]))

In [13]:
#indexing and slicing
a1[0] , a2[0,:] ,a2[:,1]

(2, array([1, 4, 8, 9]), array([4, 3]))

In [14]:
#comparison of array
a1 == a1i,a2 == a2i

(array([False, False, False, False,  True]),
 array([[False,  True, False, False],
        [ True,  True, False, False]]))

In [15]:
#computing sum, minimum, maxmim, and difference
a1, np.sum(a1), np.max(a1),np.min(a1), np.diff(a1),np.argmax(a1),np.argmin(a1)

(array([ 2,  4,  5,  7, 11]), 29, 11, 2, array([2, 1, 2, 4]), 4, 0)

In [17]:
#statistical computation

np.mean(a1),np.std(a1)

(5.8, 3.0594117081556713)

# **Using scikit-learn iris dataset**

In [18]:
from sklearn.datasets import *
import pandas as pd

**load dataset and search for keys**

In [19]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

Explore keys

In [40]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [33]:
iris.target_names, iris.feature_names

(array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [22]:
iris.data.shape

(150, 4)

**load data using pandas frame**

In [38]:
ir = pd.DataFrame(iris.data)
ir.columns = iris.feature_names
ir['CLASS'] = iris.target
#ir['CLASS_NAME'] =iris.target_names
ir.head(150)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     CLASS  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8353330611669465054, *['index'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8353330611669465054, *['sepal length (cm)'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8353330611669465054, *['sepal width (cm)'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8353330611669465054, *['petal length (cm)'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8353330611669465054, *['index'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8353330611669465054, *['sepal length (cm)'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8353330611669465054, *['sepal width (cm)'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8353330611669465054, *['petal length (cm)'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_8353330611669465054, *[[['index', 'sepal length (cm)'], ['sepal length (cm)', 'sepal width (cm)'], ['sepal width (cm)', 'petal length (cm)'], ['petal length (cm)', 'petal width (cm)']]], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8353330611669465054, *['index', 'sepal length (cm)', None], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8353330611669465054, *['index', 'sepal width (cm)', None], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8353330611669465054, *['index', 'petal length (cm)', None], **{})
chart

import numpy as np
from google.colab import autoviz
df_8353330611669465054 = autoviz.get_registered_df('df_8353330611669465054')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8353330611669465054, *['index', 'petal width (cm)', None], **{})
chart

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
